# docker-compose.yml - Configuración optimizada Open Music Bot

services:
  lavalink:
    image: fredboat/lavalink:4.0.8
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./lavalink-config/application.yml:/opt/Lavalink/application.yml:ro
    environment:
      - _JAVA_OPTIONS=-Xmx512m
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 2333 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  open-music:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-music-bot
    restart: unless-stopped
    
    # Recursos limitados para optimización
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    environment:
      # Discord
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - GUILD_ID=${GUILD_ID:-}
      
      # Audio
      - DEFAULT_VOLUME=0.5
      - OPUS_BITRATE=128000
      - FRAME_SIZE=960
      - MAX_SONG_DURATION=7200
      
      # Performance
      - CACHE_SIZE=100
      - AUDIO_CACHE_SIZE=50
      - MAX_QUEUE_SIZE=1000
      - WORKER_THREADS=2
      - MAX_PLAYLIST_SIZE=100
      
      # Features
      - ENABLE_EQUALIZER=true
      - ENABLE_AUTOPLAY=false
      
      # Lavalink
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=youshallnotpass
      
      # YouTube API (opcional con Lavalink)
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      
      # Sistema
      - RUST_LOG=info,open_music=debug
      - RUST_BACKTRACE=1
    
    depends_on:
      - lavalink
    
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./config:/home/openmusic/.config/yt-dlp
    
    # Red configurada
    ports:
      - "8080:8080"  # Puerto para métricas si fuera necesario
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "open-music"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    
    # Seguridad
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=10M
    
    # Logging optimizado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

# Volúmenes con configuración específica
volumes:
  data:
    driver: local
  cache:
    driver: local