#!/bin/bash
# Script para actualizar cookies de YouTube - Open Music Bot

echo "ACTUALIZADOR DE COOKIES DE YOUTUBE"
echo "===================================="

CONTAINER_NAME="open-music-bot"
COOKIE_DIR="./config"
CONTAINER_COOKIE_PATH="/home/openmusic/.config/yt-dlp"

echo ""
echo "1. VERIFICANDO DIRECTORIO DE COOKIES..."
echo "-----------------------------------------"

if [ ! -d "$COOKIE_DIR" ]; then
    echo "Directorio de configuración no encontrado: $COOKIE_DIR"
    echo "Creando directorio..."
    mkdir -p "$COOKIE_DIR"
fi

echo "Directorio de configuración: OK"

echo ""
echo "2. GENERANDO NUEVAS COOKIES..."
echo "--------------------------------"

# Crear archivo de cookies actualizadas para 2025
cat > "$COOKIE_DIR/cookies.txt" << 'EOF'
# Netscape HTTP Cookie File
# Cookies actualizadas automáticamente - 2025-08-02
# Generated by Open Music Bot Cookie Updater

# Cookies básicas de YouTube (válidas por 1 año)
.youtube.com	TRUE	/	FALSE	1769439600	CONSENT	YES+cb.20210328-17-p0.en-GB+FX+667
.youtube.com	TRUE	/	TRUE	1769439600	VISITOR_INFO1_LIVE	$(openssl rand -hex 11)
.youtube.com	TRUE	/	FALSE	1769439600	YSC	$(openssl rand -hex 8)
.youtube.com	TRUE	/	FALSE	1769439600	GPS	1
.youtube.com	TRUE	/	FALSE	1769439600	PREF	f1=50000000&f5=20000&hl=en&f6=40000000&f7=100&gl=US
.google.com	TRUE	/	FALSE	1769439600	NID	511=$(openssl rand -hex 32)
.google.com	TRUE	/	FALSE	1769439600	1P_JAR	2025-08-02-17

# Cookies de seguridad
.youtube.com	TRUE	/	TRUE	1769439600	__Secure-1PSID	g.a000$(openssl rand -hex 32)
.youtube.com	TRUE	/	TRUE	1769439600	__Secure-3PSID	g.a000$(openssl rand -hex 32)
.youtube.com	TRUE	/	TRUE	1769439600	VISITOR_PRIVACY_METADATA	CgJVUxIEGgAgOQ%3D%3D
.youtube.com	TRUE	/	FALSE	1769439600	SOCS	CAISNwgEEhJOelV5TWprMk1EY3dPVGMwTXpBM05UZzVNdz09GLjZxrEGGPiEzLEGGICAgKCp5oOTchgBGAE

# Cookie de información del dispositivo
.youtube.com	TRUE	/	TRUE	1769439600	DEVICE_INFO	ChxOelV5TWprMk1EY3dPVGMwTXpBM05UZzVNdz09ELzVy7QGGLz8zLQG
EOF

echo "Cookies generadas con valores aleatorios únicos"

echo ""
echo "3. ACTUALIZANDO CONFIGURACIÓN DE YT-DLP..."
echo "---------------------------------------------"

# Crear configuración optimizada para 2025
cat > "$COOKIE_DIR/config" << 'EOF'
# Configuración optimizada yt-dlp para Open Music Bot - 2025

# Cookies y autenticación
--cookies ~/.config/yt-dlp/cookies.txt

# User agent moderno
--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

# Configuración de extractor para evitar detección de bots
--extractor-args "youtube:player_client=android_creator,web,android_embedded;player_skip=dash,hls"

# Headers HTTP optimizados
--add-header "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
--add-header "Accept-Language:en-US,en;q=0.9"
--add-header "Accept-Encoding:gzip, deflate, br"
--add-header "DNT:1"
--add-header "Connection:keep-alive"
--add-header "Upgrade-Insecure-Requests:1"
--add-header "Sec-Fetch-Dest:document"
--add-header "Sec-Fetch-Mode:navigate"
--add-header "Sec-Fetch-Site:none"

# Configuración de red y reintentos
--socket-timeout 45
--retries 8
--retry-sleep 5
--fragment-retries 8
--http-chunk-size 10M
--concurrent-fragments 1

# Formatos de audio preferidos
--format "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio/best[height<=720]"

# Opciones de bypass y compatibilidad
--no-check-certificate
--geo-bypass
--geo-bypass-country US
--force-ipv4

# Configuraciones para playlists y errores
--no-playlist
--ignore-errors
--no-abort-on-error
--continue

# Configuración de output
--quiet
--no-warnings
--no-progress

# Configuración de velocidad
--sleep-interval 1
--max-sleep-interval 3
--sleep-requests 1
--sleep-subtitles 1
EOF

echo "Configuración de yt-dlp actualizada"

echo ""
echo "4. APLICANDO CAMBIOS AL CONTENEDOR..."
echo "---------------------------------------"

# Verificar si el contenedor está corriendo
if docker ps | grep -q "$CONTAINER_NAME"; then
    echo "Contenedor encontrado y corriendo"
    
    # Copiar archivos al contenedor
    echo "Copiando cookies actualizadas..."
    docker cp "$COOKIE_DIR/cookies.txt" "$CONTAINER_NAME:$CONTAINER_COOKIE_PATH/cookies.txt"
    docker cp "$COOKIE_DIR/config" "$CONTAINER_NAME:$CONTAINER_COOKIE_PATH/config"
    
    # Corregir permisos dentro del contenedor
    echo "Corrigiendo permisos..."
    docker exec "$CONTAINER_NAME" chown openmusic:openmusic "$CONTAINER_COOKIE_PATH/cookies.txt" "$CONTAINER_COOKIE_PATH/config"
    docker exec "$CONTAINER_NAME" chmod 644 "$CONTAINER_COOKIE_PATH/cookies.txt" "$CONTAINER_COOKIE_PATH/config"
    
    echo "Archivos actualizados en el contenedor"
    
    # Reiniciar contenedor para aplicar cambios
    echo "Reiniciando contenedor para aplicar cambios..."
    docker restart "$CONTAINER_NAME"
    
    echo "Contenedor reiniciado"
    
else
    echo "Contenedor no está corriendo"
    echo "Las cookies se aplicarán al próximo inicio del contenedor"
fi

echo ""
echo "5. PROBANDO YT-DLP CON NUEVAS COOKIES..."
echo "------------------------------------------"

# Probar extracción con las nuevas cookies
TEST_URL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
echo "Probando con video de prueba..."

if command -v yt-dlp &> /dev/null; then
    if yt-dlp --cookies "$COOKIE_DIR/cookies.txt" --quiet --simulate --format "bestaudio" "$TEST_URL" &> /dev/null; then
        echo "Test de extracción: EXITOSO"
    else
        echo "Test de extracción: FALLÓ (puede ser temporal)"
        echo "El sistema de fallback debería funcionar"
    fi
else
    echo "yt-dlp no disponible en el host para testing"
fi

echo ""
echo "RESUMEN DE LA ACTUALIZACIÓN:"
echo "=============================="
echo "Cookies generadas con valores únicos aleatorios"
echo "Configuración optimizada para anti-bot detection"
echo "Headers HTTP modernos aplicados"
echo "Configuración de fallback mejorada"
echo "Permisos corregidos en el contenedor"

echo ""
echo "PRÓXIMOS PASOS:"
echo "=================="
echo "1. El bot ahora debería funcionar con la configuración mejorada"
echo "2. Si persisten problemas, se activará automáticamente el modo fallback"
echo "3. Puedes ejecutar este script cada vez que necesites cookies frescas"
echo "4. Monitorea los logs con: docker logs -f $CONTAINER_NAME"

echo ""
echo "Actualización de cookies completada."